### ISSUE TITLE
Confusing readings for cellPercent

### ISSUE THREAD

**Issue by caternuson** [adafruit/Adafruit_LC709203F#2]
Re this thread:
https://forums.adafruit.com/viewtopic.php?f=19&t=170429

Also recreated locally running library demo. Voltage agrees with multimeter reading. Ignoring temperature reading. Percentage seems odd though. Seems like it should be higher, assuming 4.2V to be the nominal 100%.
![Screenshot from 2020-10-15 11-21-36](https://user-images.githubusercontent.com/8755041/96170751-db4e5200-0ed8-11eb-8adb-6a2ae48cf47c.png)

**Comment by ladyada** [comment]
hmm ive plugged a battery in and am charging it, will see whats up, the chip is not very complex, probably some incorrect math or register setting. the percentage comes from a register read

**Comment by DaveBKC** [comment]
Maybe worth noting: I didn't test this with CircuitPython, only Arduino.  Maybe CircuitPython math is ok?

**Comment by DaveBKC** [comment]
Any news on this sucker?

**Comment by ladyada** [comment]
yah turns out it defaults to thinking the battery is 4.35V instead fo the common 4.2V - latest commit fixes it to assume 4.2V and % should be more familiar!
