### ISSUE TITLE
Would like better control in specifying battery pack size (APA)

### ISSUE THREAD

**Issue by disquisitioner** [adafruit/Adafruit_LC709203F#6]
I wish you hadn't made the battery pack size (APA) factor an enum (lc709203_adjustment_t) as that makes it impractical for me to use values other than what you've defined in the enum, even though I can easy interpolate more accurate APA values from the curve in the LC709203F datasheet.  (E.g., for a 1200 mAH battery pack an APA value of 0x1D would be more accurate than having to use the 1000 mAH value in the enum.).

**Comment by ladyada** [comment]
hiya you could add a new function that takes a uint8_t then people can pick any number they want, and submit a PR :)

**Comment by disquisitioner** [comment]
Happy to do that!  Thanks.

**Comment by disquisitioner** [comment]
Pull request submitted.

**Comment by ladyada** [comment]
thanks! please check the CI output to get it ready for review and then we can merge :)

**Comment by Seikonolff** [comment]
Hello there,

Bringing this back as I don't get why @disquisitioner 's setPackAPA function takes a 8 bits int as parameter while casting it to a 16 bits when using the writeWord function. 
For ex when I use it for a 5000 mAh battery the value is changed to 136 (5000%256).
